name: Email Session Test
author: Jason Kayembe
description: This test launches an email session scenario with adblock

services:
    automated-session:
        image: jkayembe/automated-session
        ports:
            - 5900:5900
        environment:
          IS_MEASURED: "true"
          SEED: 123
        shell: "bash"
        setup-commands:
            - cp -R /app/chrome_profiles /chrome_profiles
            - Xvfb :0 -screen 0 1296x736x16 & # X Server : simulate graphic card in memory. (The html pages are unpredictable in headless mode)
            #- x11vnc -forever -create -display :0 -rfbport 5900 -bg -nopw # VNC server : It connects to the X server and send the GUI on port 5900. Use for Debbugging
        folder-destination: "/app"
        command: "bash"

flow:
    - name: Run the scenario
      container: automated-session
      commands:
        - type: console
          command: python src/scenario.py test/2_gmail_answer_adblock.json
          note: Starting the Python Scenario Script
          log-stdout: true
          read-notes-stdout: true
          log-stderr: true
        - type: console
          command: sleep 10
          note: Idling
